name = "aliyun-cdt-tracker"
main = "src/index.js"
compatibility_date = "2024-04-05"

# 环境变量 (Environment Variables)
# 请在 Cloudflare Dashboard 中设置这些变量，不要直接写在这里，以防泄露
# ACCESS_KEY_ID
# ACCESS_KEY_SECRET
# REGION_ID
# ECS_INSTANCE_ID
# TRAFFIC_THRESHOLD_GB

[observability]
[observability.logs]
enabled = true
invocation_logs = true

[triggers]
crons = ["* * * * *"] # 每1分钟运行一次，可根据需要调整
